name: Build LaTeX document
on:
   pull_request:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          args: "-pdf -file-line-error -interaction=nonstopmode --shell-escape"
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: "master thesis"
          path: ./main.pdf
